a = input("Введите число")
f =  a.replace("1" , "0")
g = f.replace("2" , "0")
h = g.replace("3" , "0")
j = h.replace("4" , "0")
k = j.replace("5" , "1")
l = k.replace("6" , "1")
m = l.replace("7" , "1")
n = m.replace("8" , "1")
b = n.replace("9" , "1")
print(b)